name: sscce
summary: A short, self-contained complete example of a Python snap build
description: |
    sscce is a short, self-contained complete example of a Python snap build.
version: test
base: core24
confinement: strict

parts:
  sscce:
    plugin: python
    source: .
    # I want the benefits of Ubuntu LTS packages, thus am choosing to use them
    # instead of pulling the latest code from PyPI.
    stage-packages:
      - python3-typer

apps:
  sscce:
    command: bin/python $SNAP/bin/sscce
    environment:
      PYTHONPATH: "$SNAP/usr/lib/python3/dist-packages"